### ISSUE TITLE
Rate limit doesn't always block my requests when needed

### ISSUE THREAD

**Issue by yanivshiloah** [krakendio/krakend-ratelimit#30]
Hey, I have the following configuration:
```

        "qos/ratelimit/router": {
          "client_max_rate": 0.0167,
          "client_capacity": 20,
          "strategy": "header",
          "key": "x-account-id"
        }
```

If I understand correctly, this should allow me accessing the relevant endpoint only 20 times an hour.
When I test it, I do see that after 20 times it starts blocking my requests, but then I wait only a few seconds and try again, it sometimes goes thru and misses the rate limiting.

Could it be related to the header i'm using? 
The header is passed to the request using the "propagate_claims" in "auth/validator" extra-config.

I don't see any issue in the log.

**Comment by kpacha** [comment]
please, read the documentation carefully (https://www.krakend.io/docs/throttling/token-bucket/#how-the-token-bucket-algorithm-works). the capacity is the max amount of tokens that could be available and the max_rate is the rate of refilling tokens into the bucket until the capacity is reached. also, at the initial state the bucket is full. that's why you can send an initial burst of 20 requests before the spike arrest kicks in. Once there are no more tokens at the bucket, the system will allow you to send 1 request every minute aprox (1/0.0167=59.88).

**Comment by yanivshiloah** [comment]
Got it, thanks a lot, I now understand it much better. 
Sorry and have a great day!
